SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM (SELECT *
      FROM BOOK_SALES
      WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1) BS JOIN 
      BOOK B ON BS.BOOK_ID = B.BOOK_ID JOIN
      AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC