WITH RECURSIVE GEN_CTE AS(
    -- 1세대 정의
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID,
        G.GENERATION + 1
    FROM ECOLI_DATA E JOIN GEN_CTE G ON E.PARENT_ID = G.ID
) 
SELECT ID
FROM GEN_CTE
WHERE GENERATION = 3
ORDER BY ID