SELECT P.PRODUCT_CODE, P.PRICE * TMP.AMOUNT AS SALES
FROM PRODUCT AS P JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
                        FROM OFFLINE_SALE
                        GROUP BY PRODUCT_ID) AS TMP
                  ON P.PRODUCT_ID = TMP.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE