SELECT TMP1.CAR_ID, 
       TMP1.CAR_TYPE,  
       ROUND(TMP1.DAILY_FEE * ((100 - TMP2.DISCOUNT_RATE) / 100) * 30) AS FEE
FROM 
    -- 조인 테이블1: 원하는 기간에 빌릴 수 있는 차
    (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
                SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')) TMP1
    JOIN 
    -- 조인 테이블2: 차종별 30일 대여의 할인율
    (SELECT CAR_TYPE, DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE DURATION_TYPE = '30일 이상') TMP2
    ON TMP1.CAR_TYPE = TMP2.CAR_TYPE
-- 필터링: 원하는 차종만, 대여금이 50이상 200 미만
WHERE TMP1.CAR_TYPE IN ('세단', 'SUV') 
      AND 500000 <= TMP1.DAILY_FEE * (100 - TMP2.DISCOUNT_RATE) / 100 * 30
      AND TMP1.DAILY_FEE * (100 - TMP2.DISCOUNT_RATE) / 100 * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
      