SELECT ID,
        CASE
        WHEN RANK_NUM <= COUNT(*) OVER () * 0.25 THEN 'CRITICAL'
        WHEN RANK_NUM <= COUNT(*) OVER () * 0.5 THEN 'HIGH'
        WHEN RANK_NUM <= COUNT(*) OVER () * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
        END AS COLONY_NAME
FROM (SELECT *, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_NUM
      FROM ECOLI_DATA) ECOLI_DATA
ORDER BY ID

