WITH UI AS (
  SELECT *
  FROM USER_INFO
  WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'),
TOTAL AS (
  SELECT COUNT(*) AS total_users
  FROM UI
)

SELECT YEAR(OS.SALES_DATE) AS YEAR, 
        MONTH(OS.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS,
        ROUND( COUNT(DISTINCT UI.USER_ID) / (SELECT COUNT(*) FROM UI), 1) AS PURCHASED_RATIO
FROM UI JOIN ONLINE_SALE AS OS
        ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH