SELECT TMP1.HISTORY_ID,
       ROUND(TMP1.DAILY_FEE * ((100 - IFNULL(TMP2.DISCOUNT_RATE, 0)) / 100) * TMP1.DURATION) AS FEE
FROM -- 조인 테이블1: 트럭 대여정보와 대여기간, 대여기간에 따른 할인대상기간
    (SELECT RH.HISTORY_ID, 
             CC.CAR_TYPE,
             CC.CAR_ID,
             CC.DAILY_FEE,
             DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
             CASE
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN 90
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN 30
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN 7
             ELSE 0
             END AS DURATION_TYPE
     FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON CC.CAR_ID = RH.CAR_ID
     WHERE CAR_TYPE = '트럭') TMP1 
     LEFT JOIN
     -- 조인 테이블2: 트럭 대상 대여기간 별 할인율 
     (SELECT CAR_TYPE,
             CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS SIGNED) AS DURATION_TYPE,
             DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
     WHERE CAR_TYPE = '트럭'
     ORDER BY DURATION_TYPE) TMP2
     ON 
     TMP1.DURATION_TYPE = TMP2.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC

     
