SELECT
    FLAVOR
FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SALES
     FROM FIRST_HALF
     GROUP BY FLAVOR
     
     UNION ALL
     
     SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SALES
     FROM JULY
     GROUP BY FLAVOR) AS TEMP
GROUP BY FLAVOR
ORDER BY SUM(TEMP.TOTAL_SALES) DESC
LIMIT 3;