-- 재귀 CTE로 기준 테이블 만들기(0~23시)
WITH RECURSIVE B_TABLE (HOUR) AS(
    -- 시작점 설정
    SELECT 0
    UNION ALL
    -- 반복 조건 설정
    SELECT HOUR + 1 FROM B_TABLE WHERE HOUR < 23 
)
-- 원하는 결과를 구하고 기준 테이블에 LEFT JOIN
SELECT B.HOUR, IFNULL(A.COUNT, 0) AS COUNT
FROM B_TABLE B LEFT JOIN
    (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
     FROM ANIMAL_OUTS
     GROUP BY HOUR(DATETIME)
     ORDER BY HOUR) A ON B.HOUR = A.HOUR

