SELECT II2.ITEM_ID, II2.ITEM_NAME, II2.RARITY
-- 조인: 나의 다음 단계 아이템(나를 부모로 갖는)을 오른쪽에 붙임
FROM ITEM_INFO II LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
                  LEFT JOIN ITEM_INFO II2 ON IT.ITEM_ID = II2.ITEM_ID
WHERE II.RARITY = 'RARE' AND II2.ITEM_ID IS NOT NULL
ORDER BY II2.ITEM_ID DESC