SELECT MONTH, CAR_ID, SUM(RENTAL_COUNT) AS RECORDS
FROM -- 차별, 월별 렌탈횟수
    (SELECT CAR_ID, MONTH(START_DATE) AS MONTH, COUNT(*) AS RENTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    -- 그룹화 전 필터링1: 8~10월 사이 총 대여횟수가 5회 이상인 자동차들의 8~10월 데이터만!
    WHERE CAR_ID IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE '2022-08-01' <= START_DATE AND START_DATE <= '2022-10-31'
                    GROUP BY CAR_ID
                    HAVING COUNT(*) >= 5)
                AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID, MONTH(START_DATE)) TMP
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC