SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    -- 윈도우 함수: 연도별(PARTITION BY) 최대 크기를 각 행에 계산하여 붙임
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE))) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA
ORDER BY
    YEAR, YEAR_DEV;

    