SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
                                   ON CAR.CAR_ID = HIS.CAR_ID
WHERE CAR.CAR_TYPE = '세단' AND HIS.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CAR.CAR_ID DESC